export const tarot_map = {
    0: { ru: "Дурак", en: "Fool" },
    1: { ru: "Маг", en: "Magician" },
    2: { ru: "Жрица", en: "High Priestess" },
    3: { ru: "Императрица", en: "Empress" },
    4: { ru: "Император", en: "Emperor" },
    5: { ru: "Иерофант", en: "Hierophant" },
    6: { ru: "Влюблённые", en: "Lovers" },
    7: { ru: "Колесница", en: "Chariot" },
    8: { ru: "Сила", en: "Strength" },
    9: { ru: "Отшельник", en: "Hermit" },
    10: { ru: "Колесо Фортуны", en: "Wheel of Fortune" },
    11: { ru: "Справедливость", en: "Justice" },
    12: { ru: "Повешенный", en: "Hanged Man" },
    13: { ru: "Смерть", en: "Death" },
    14: { ru: "Умеренность", en: "Temperance" },
    15: { ru: "Дьявол", en: "Devil" },
    16: { ru: "Башня", en: "Tower" },
    17: { ru: "Звезда", en: "Star" },
    18: { ru: "Луна", en: "Moon" },
    19: { ru: "Солнце", en: "Sun" },
    20: { ru: "Суд", en: "Judgment" },
    21: { ru: "Мир", en: "World" }
};
